name: Build Vuejs project
on:
  push:
    branches:
      - develop
jobs:  
  deploy:
    name: "Deploy to EC2 instance"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}

      - name: Bring changes
        run: ssh staging 'cd /home/ubuntu/licenciatura/licenciatura-frontend && git pull'
        
      - name: Deploy for production
        run: ssh staging 'cd /home/ubuntu/licenciatura/licenciatura-frontend && npm run build'
      
      - name: Serve changes
        run: ssh staging 'sudo rm -r /var/www/html/* && sudo mv --force /home/ubuntu/licenciatura/licenciatura-frontend/dist/* /var/www/html/'
