name: Build Vuejs project
on:
  push:
    branches:
      - develop
jobs:
  artifact:
    name: Create the mvn artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 1.11
      - name: Build Maven project
        run: |
          mvn package --file ./lib/pom.xml -Dmaven.test.skip
          mkdir staging && cp target/*.jar staging
      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging
  publish:
    name: Deploy to github packages
    needs: artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 1.11
      - name: deploy package
        run: mvn --batch-mode deploy -Dmaven.test.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trigger_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend workflow
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/kebblar/licenciatura-backend/dispatches --data '{"event_type": "build_application"}'
